### ISSUE TITLE
LeetFlash cannot be installed

### ISSUE THREAD

**Issue by supertom495** [q815101630/LeetFlash#5]
An error has occurred
Package is invalid. Details: 'Could not load icon 'iconOnly2.png' specified in 'icons'.'.

OS: PopOs 22.04
Browser: Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by lucheng-hugh** [comment]
@supertom495 Thanks for reporting. It is weird that my Windows laptop works fine. I later tried with my Ubuntu VM and it reports the error. The error is due to a misspelling in `manifest.json`. It's pretty interesting why it works well on Windows but not on Linux... Anyway, I have fixed the bug in the newest commit. I will notify you in this issue once the extension is available in the Extension Store

**Comment by lucheng-hugh** [comment]
@supertom495 new version is available, please download again and see if it's working now

**Comment by supertom495** [comment]
@q815101630 It's working fine now. Closing the ticket. Thanks!
